project:
  name: deployment-monitoring
  description: Stack Prometheus + Grafana pour monitoring des services de déploiement automatique
  repository: nekocheik/deployment-monitoring-ops
  
deployment:
  # Configuration multi-services
  services:
    - name: metrics-exporter
      port: 9091
      exposed: true
      subdomain: metrics
      health_check: /health
      description: "Exporteur de métriques pour Prometheus"
    - name: grafana-proxy
      port: 3001
      exposed: true
      subdomain: grafana
      health_check: /api/health
      description: "Interface Grafana simulée"
    - name: nginx-reverse-proxy
      port: 80
      exposed: true
      subdomain: null  # Service principal
      health_check: /health
      description: "Reverse proxy principal et dashboard"
      
  ports:
    allocated: null  # Sera alloué automatiquement par port-manager
    fallback: 3000
    manager:
      enabled: true
      url: http://localhost:3005
      remote_url: http://51.159.99.160:3005
      multi_service_support: true
      
  environments:
    main:
      domain: monitoring.silverhawk77.click
      ssl: true
      auto_deploy: true
    develop:
      domain: dev-monitoring.silverhawk77.click
      ssl: false
      auto_deploy: false
    staging:
      domain: staging-monitoring.silverhawk77.click
      ssl: false
      auto_deploy: false
    production:
      domain: monitoring.silverhawk77.click
      ssl: true
      auto_deploy: false
      
  docker:
    image_name: deployment-monitoring
    build_context: .
    dockerfile: Dockerfile
    container_name_template: '{project}-{branch}-deploy'
    multi_service:
      enabled: true
      compose_file: docker-compose.monitoring.yml
      strategy: compose
    
  deploy:
    strategy: rolling
    health_check:
      enabled: true
      path: /health
      timeout: 60
    env_vars:
      NODE_ENV: production
      PROMETHEUS_RETENTION_TIME: 30d
      GF_SECURITY_ADMIN_PASSWORD: monitoring2024!
      
  monitoring:
    enabled: true
    metrics_port: 9091
    
metadata:
  version: 1.0.0
  created_at: '2025-08-21T10:35:00Z'
  updated_at: '2025-08-21T10:35:00Z'
  created_by: Claude Code
  template_version: monitoring-stack-v1