server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 📝 Logs système
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          host: deployment-server

  # 🔌 Port Manager logs
  - job_name: port-manager
    static_configs:
      - targets:
          - localhost
        labels:
          job: port-manager
          service: port-manager
          __path__: /var/log/port-manager/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            port: port
            project: project
            branch: branch
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          port:
          project:
          branch:

  # 🚀 Deployment API logs  
  - job_name: deployment-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: deployment-api
          service: deployment-api
          __path__: /var/log/deployment-api/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            deployment_id: deployment_id
            commit: commit
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          deployment_id:
          commit:

  # 🌩️ Tunnel Manager logs
  - job_name: tunnel-manager
    static_configs:
      - targets:
          - localhost  
        labels:
          job: tunnel-manager
          service: tunnel-manager
          __path__: /var/log/tunnel-manager/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            hostname: hostname
            container: container
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          hostname:
          container:

  # 🐳 Docker containers logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
      - output:
          source: output

  # 📊 Monitoring stack logs
  - job_name: monitoring
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoring-stack
          __path__: /var/log/monitoring/*.log